#SPDX-License-Identifier: MIT-0
---

- name: Copy MariaDB build context to remote server
  copy:
    src: "{{ role_path }}/files/"
    dest: /tmp/wordpress_build/
    mode: '0755'

- name: Build the custom Wordpress docker image
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    source: build
    build:
      path: "/tmp/wordpress_build/"
    state: present

- name: Run Wordpress Container with environment variables
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    restart_policy: unless_stopped
    env: "{{ wordpress_env }}"
    networks:
      - name: cloud_network
    exposed_ports:
      - "9000"
    volumes:
      - "data_wp:/var/www/html"