#SPDX-License-Identifier: MIT-0
---

wordpress_env:
  # certificates
  DOMAIN_NAME: "mmoumni.1337.ma"

  # MariaDb
  MYSQL_DATABASE: "wordpress_db"
  MYSQL_USER: "moumni"
  MYSQL_PASSWORD: "Moha"
  MYSQL_ROOTPASSWORD: "1234"
  HOST: "mariadb_container"

  #first wordpress User
  CERTS_: "/etc/ssl/certs/nginx-selfsigned.crt"
  KEYS_: "/etc/ssl/private/nginx-selfsigned.key"
  ADMIN_USER: "mmoumni"
  ADMIN_PASSWORD: "MohaMed"
  ADMIN_EMAIL: "mohawatch101@gmail.com"

  # Second wordpress User
  USER: "moumni2"
  USER_PASSWORD: "Moha1234"
  USER_EMAIL: "mohamedmoulin7@gmail.com"
  DISPLAY_NAME: "Rigor"

docker_image_name: wordpress_image

docker_container_name: wordpress