$ANSIBLE_VAULT;1.1;AES256
65373034313637323132343932363461326663636162303235336264623463376365363932616337
6131336338663630306162333534396564326661653864390a623665343265323964646537343734
33306364336239633835633766346339343533653139326333376539626530386234333430316431
3065616436323835390a656638363939613630333765633163636531326464323837373664316530
34663038383264643662356539646337396136613163626366383232643831623862393162393731
31336234616263666363666234373665656632336435353965643035633638626563363861333537
32653630303863353131383962333336363764653061343537343730623939363639326235616666
35303265633964333735626435623665393831343032623430626334636638643232646363303766
38663239386662613730613663376132656230363930336335626439376564613261663136323331
33663832376365383636656639623737383136336663316665613964623437316537323461323738
35656437383261626164333566656565343231393465393431353637373036336566343465333234
34666363353737373837623264623338383763383932366664363537663436373131373166316362
33653531396533366231656566343531316434353463663434323863363430633733643238616163
38653863366535616439633162623663346637323339316365646232333561333333633734333939
30316565623934396136306631393139616631333233653962303930663966663763323531383038
38386231653138656532396638616536363066653439653961646535646231636430623839343766
64656362396265656135656432616236356436376662653863343734366430363966
