$ANSIBLE_VAULT;1.1;AES256
31336138363766313133343233623834613837636333626637366264373837363862346536626238
3433303533333734353962653130633135353035646639370a386237646530393535396137633832
31303937643566656662366235363363616565616438366266336537626538326338623737383537
3162653165663561610a666233326662373634383964623362373865626435323465623666643165
37336235643138653735336139303032343766646439363464616138613932313737646239386461
38396134616164636537633663663165613431376338616139363333303338653363376132626135
38376261303435326165346630613064613332633533356537616131333966373635623232653232
61323361653661646531313931316639653838363430303562633165323639633035373132383965
64646462373236613162366664663538356563613662356332346634366538363434633630613930
64323332663630333435383063356262366639326530613165363735363666633636306461303438
32383031333462623933306534656662303333343832316639623963623830646238386633376132
33653739316662303032306136383534396262393934363732653863366462393065353431623035
64663034666430336338386238316662346133323936313030366437336335313964336239373430
34323838376438356231323831323231653461363161653632373531303564323730303533626536
38373761326562623138663937383766626135356633366466343530326162643234393130393663
38386431623039326561323831386636663366623066636166303233656636336564613261333161
33363763626265396265393964643566326634323464383034396636333737353166
