---

- name: Build the custom MariaDb docker image
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    source: build
    build:
      path: "{{ role_path }}/files"
    state: present

- name: Run MariaDb Container with environment variables
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    restart: yes
    env: "{{ mysql_env }}"
    networks:
      - name: cloud_network
    exposed_ports:
      - "3306"