---
- name: Copy MariaDB build context to remote server
  copy:
    src: "{{ role_path }}/files/"
    dest: /tmp/mariadb_build/
    mode: '0755'

- name: Build the custom MariaDb docker image
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    source: build
    build:
      path: "/tmp/mariadb_build/"
    state: present

- name: Run MariaDb Container with environment variables
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    restart_policy: unless_stopped
    env: "{{ mysql_env }}"
    networks:
      - name: cloud_network
    exposed_ports:
      - "3306"