$ANSIBLE_VAULT;1.1;AES256
62316534383766396466303332333030323935366433393935623361326430623033383761346334
6136666330346666373330353932316166373164396565300a653532653931356632383365623736
34653936656339303135316230656235646234336537366335636232373634346431343337653362
3930633064323933660a336363303736643361613337336635663934336266666261373337613134
30383531393666343435623535656561636633346261366465326238633439366330333466643838
37383464353963396238613362316134653533356263613338623831313235633261373636343531
65386233373934313336323035366137393530373838613963653462613730626137643963333264
39363266363761323937656239326261323830636234326138646436633334643737303435613733
37373930396232306132373337636231666565613839353766663631363665316462663563636538
64653337306138353337643935303661646236633839363831656332623836663234396461396139
36393233373964326432656266653433373132396635626133313630353965343133396262393064
63363930363662323338356434653465373030306431326230323337356135353834336231616633
38336563356332363434656539393733363364643265343837303063656161326265633030653631
63653135313065313866613433636432613432336536323037346539623033616339353464623935
36353630363933343239313264373532316236633438336662393864326564313034656235363633
65323962323463393936393761636561626331343463323164623537613462353264613331646330
64643230626133653530653533303332653664333639633933343366613436303432
