---

# Define environment variables for the MariaDB container
mysql_env:
  MYSQL_DATABASE: "wordpress_db"
  MYSQL_USER: "moumni"
  MYSQL_PASSWORD: "Moha"
  MYSQL_ROOTPASSWORD: "1234"


docker_image_name: mariadb_image

docker_container_name: mariadb_container