$ANSIBLE_VAULT;1.1;AES256
62626634323339366564376130353238663035643538306530656237643031623761333565383464
6563333963613631343539353034343064643130363231650a316266323436633566316264366235
63613164333634336439666133393965643961386236323566306666643462383733396236643436
6264386262623133340a626236373838343366323364626635333737303961383430653136336434
37366630386532363333376134356335623032636565323235396231306566313835313239666135
39633463343565386139363238666561633439643061363435636434363530633631393132643064
36656138326539303436633035393561383462613636646462363763396336323934336134386430
61323838373535336466366463353663646536363661666163633430346136313561343164373735
64303866643237363166613561646433316332663632313666393565366163336634393937363265
32646262343430363833653938643136326232386162633635383764336538636534646561323762
30633031616432333766393435373934376132323338333330333637383532366638383061356661
66626532393630666132396437633666323937663766313963613232346364653164346565343661
64353066626461356264323535366463613639646664633331633865613366613934663865316632
39313061396464323737323338653435363366633134653533636163373036323137363436663838
30383961336633396431363164373431633832303134613065346333653761323865613331323639
63653930306238306261383230313630333864333666383530356161663865656434383266353639
36313365323462393765316530303331663332313365396330396163643961663636
