$ANSIBLE_VAULT;1.1;AES256
66646462663333363030663965353931653235353864373538356135636533333238646334613130
6435316435613435336131633430376365356463656436350a626336316362653663396635326530
35356166333234373463396331653539376262623237333035656561353137343931613264323331
3161343964353433650a353936306630613037616565633039333530646538353764313866633532
39633265366538623436306632643037363035373962656662396635333236616130623537393438
39643663653166613238663635393663393162623736613664616137356435353264363338313439
32616133333731356632363264613165623336306338383966306139373433316638396530316463
63396464313563396263333935353062666534393735656130653363373733653666623833353632
31333364643865663832333463343939303831623266613830366139666236643663366666643734
30333137303662616164323539643564626136383139356233323732396565613761396565393162
36396638303734326535383339653435366536363830396633353430613938633531613433326335
34313836383835373564306363623335633534373237616438613733353635393239356631376632
39386634643162613835663162343134323566613735383135363037356239643831343564626164
3833363165363638616338326661623231613463356636636161
