#SPDX-License-Identifier: MIT-0
---
# tasks file for webserver

- name: Copy MariaDB build context to remote server
  copy:
    src: "{{ role_path }}/files/"
    dest: /tmp/webserver_build/
    mode: '0755'

- name: Build the custom Ngnix docker image
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    source: build
    build:
      path: "/tmp/webserver_build/"
    state: present

- name: Run Ngnix Container with environment variables
  community.docker.docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    restart: yes
    env: "{{ webserver_env }}"
    networks:
      - name: cloud_network
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "data_wp:/var/www/html"